/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

import com.github.pheerathach.ThaiQRPromptPay;
import com.google.zxing.WriterException;
import component.BillCash;

import component.BillQrCode;

/**
 *
 * @author DELL
 */
public class CheckBill extends javax.swing.JPanel {

    /**
     * Creates new form CheckBill
     */
    static final  String QrPath = System.getProperty("user.dir")
                                +"//DB//Pic//Qr.png";

    public CheckBill() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButtonCard = new javax.swing.JButton();
        jButtonCash = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jReceipt = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setBackground(new java.awt.Color(235, 235, 235));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCard.setBackground(new java.awt.Color(244, 103, 0));
        jButtonCard.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jButtonCard.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCard.setText("Prompt Pay");
        jButtonCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCardActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 600, 80));

        jButtonCash.setBackground(new java.awt.Color(244, 103, 0));
        jButtonCash.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jButtonCash.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCash.setText("Pay Bill Cash");
        jButtonCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCashActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 600, 80));

        jButtonBack.setBackground(new java.awt.Color(244, 103, 0));
        jButtonBack.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Return");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 190, 70));

        jButton1.setBackground(new java.awt.Color(244, 103, 0));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 190, 70));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setText("Please select a payment .");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 570, 50));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 640, 680));

        jReceipt.setColumns(20);
        jReceipt.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jReceipt.setRows(5);
        jReceipt.setText("null");
        jReceipt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jReceiptMouseDragged(evt);
            }
        });
        jReceipt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jReceiptKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jReceiptKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jReceipt);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 540, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCardActionPerformed
        ThaiQRPromptPay qr = new ThaiQRPromptPay.Builder()
        .dynamicQR()
        .creditTransfer()
        .mobileNumber("0816163850")
        .amount(new BigDecimal(Menu.getTotalPrice()))
        .build();
        try {
            qr.draw(500, 500, new File(QrPath));
            System.out.print("qrcode sucess ");//check make images success
        } catch (IOException e) {
            e.printStackTrace();return;
        } catch (WriterException e) {
            e.printStackTrace();return;
        }
        //show qr code
        try {
            //readImage by path 
            BufferedImage img = ImageIO.read(new File(QrPath));
            BillQrCode.jLabelQrCode.setIcon(new ImageIcon(img));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Index.jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jButtonCardActionPerformed

    private void jButtonCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCashActionPerformed
         BillCash.LabelCashTotal.setText(Menu.getTotalPrice());
        Index.jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButtonCashActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu.endOrder();
        Index.jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        Index.jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jReceiptKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jReceiptKeyTyped
        evt.consume();
    }//GEN-LAST:event_jReceiptKeyTyped

    private void jReceiptMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jReceiptMouseDragged
        evt.consume();
    }//GEN-LAST:event_jReceiptMouseDragged

    private void jReceiptKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jReceiptKeyPressed
                evt.consume();
    }//GEN-LAST:event_jReceiptKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCard;
    private javax.swing.JButton jButtonCash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JTextArea jReceipt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
