/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import javaDB.PosDB;
import javax.swing.ImageIcon;
import java.awt.Image;


public class Index extends javax.swing.JFrame {

    public static PosDB db = new PosDB(); // new object 
    public static final String MAIN_DISH = "main dish";
    public static final String DESSERT = "dessert";
    public static final String DRINK = "drink";
    
    //Picture Logo
//    private static final String IMAGE_PATH_LOGO = "C:\\Users\\potcj\\Desktop\\FinalProject\\src\\main\\java\\pictures\\Background1.gif";
    public static boolean haveOrder = false;
    public static boolean haveConfigMenu = false;
    
    public Index() {
        initComponents();
    }
    //clean code    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();
        jPageEdit = new javax.swing.JButton();
        jPageHistory = new javax.swing.JButton();
        jPageMenu = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        menu1 = new main.Menu();
        addMenu1 = new component.AddMenu();
        checkBill1 = new main.CheckBill();
        billCash1 = new component.BillCash();
        billQrCode1 = new component.BillQrCode();
        menuConfig1 = new main.MenuConfig();
        history1 = new main.History();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        setResizable(false);
        setTitle("CS Brew Coffee Pos");;

        jPanel2.setBackground(new java.awt.Color(204, 255, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton16.setBackground(new java.awt.Color(244, 103, 0));
        jButton16.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setIcon(new javax.swing.ImageIcon("DB\\Pic\\logo.gif")); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 210));

        jPageMenu.setBackground(new java.awt.Color(244, 103, 0));
        jPageMenu.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jPageMenu.setForeground(new java.awt.Color(255, 255, 255));
        jPageMenu.setText("Menu");
        jPageMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPageMenuActionPerformed(evt);
            }
        });
        jPanel2.add(jPageMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 210, 70));

        jPageEdit.setBackground(new java.awt.Color(244, 103, 0));
        jPageEdit.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jPageEdit.setForeground(new java.awt.Color(255, 255, 255));
        jPageEdit.setText("Edit Menu");
        jPageEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPageEditActionPerformed(evt);
            }
        });
        jPanel2.add(jPageEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, 70));

        jPageHistory.setBackground(new java.awt.Color(244, 103, 0));
        jPageHistory.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jPageHistory.setForeground(new java.awt.Color(255, 255, 255));
        jPageHistory.setText("History");
        jPageHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPageHistoryActionPerformed(evt);
            }
        });
        jPanel2.add(jPageHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 210, 70));

        jButtonExit.setBackground(new java.awt.Color(244, 103, 0));
        jButtonExit.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 210, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 790));

        jTabbedPane1.addTab("tab1", menu1);
        jTabbedPane1.addTab("tab2", addMenu1);
        jTabbedPane1.addTab("tab3", checkBill1);
        jTabbedPane1.addTab("tab4", billCash1);
        jTabbedPane1.addTab("tab5", billQrCode1);
        jTabbedPane1.addTab("tab6", menuConfig1);
        jTabbedPane1.addTab("tab7", history1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -40, 1390, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
//        ImageIcon logoIcon = new ImageIcon (new ImageIcon(IMAGE_PATH_LOGO).getImage().getScaledInstance(200, 150, Image.SCALE_SMOOTH));
//        jButton16.setIcon(logoIcon);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jPageEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPageEditActionPerformed
         jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_jPageEditActionPerformed

    private void jPageMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPageMenuActionPerformed
        if (haveConfigMenu) {
            Menu.addMenuGrid();
            haveConfigMenu = false;
        }
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jPageMenuActionPerformed

    private void jPageHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPageHistoryActionPerformed
       if (haveOrder) {
            History.createHistoryTable();
            haveOrder = false;
        }
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_jPageHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.AddMenu addMenu1;
    public static main.Menu menu1;
    private main.MenuConfig menuConfig1;
    private main.History history1;
    private component.BillCash billCash1;
    private component.BillQrCode billQrCode1;
    private main.CheckBill checkBill1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jPageEdit;
    private javax.swing.JButton jPageHistory;
    private javax.swing.JButton jPageMenu;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
