/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import static main.Index.jTabbedPane1;

import javax.swing.DefaultListModel;

import main.Index;
import main.Menu;

/**
 *
 * @author DELL
 */
public class AddMenu extends javax.swing.JPanel {

    /**
     * Creates new form addMenu
     */
    public AddMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jFormattedAmount = new javax.swing.JFormattedTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(235, 235, 235));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel25.setText("Price : ");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 80, 40));

        jLabelName.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabelName.setText("Name Menu");
        jPanel3.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jLabelPrice.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabelPrice.setText("40.00");
        jPanel3.add(jLabelPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, 40));

        jButtonAdd.setBackground(new java.awt.Color(244, 103, 0));
        jButtonAdd.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setText("Add Menu");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonBack.setBackground(new java.awt.Color(244, 103, 0));
        jButtonBack.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Cancel");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 650, 90));

        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTextField1.setText("Enter Comment Food");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 530, 170));

        jFormattedAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedAmount.setText("1");
        jFormattedAmount.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jFormattedAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedAmountMouseClicked(evt);
            }
        });
        jFormattedAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedAmountActionPerformed(evt);
            }
        });
        jFormattedAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedAmountKeyTyped(evt);
            }
        });
        jPanel3.add(jFormattedAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 160, 40));

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel29.setText("Count ");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel26.setText("Note :");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 90, 40));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 53, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        String name = jLabelName.getText();
        int amount = Integer.valueOf(jFormattedAmount.getText());

        if(!Menu.menuNow.containsKey(name)){
        //add menu in list
        Menu.model.addElement(name +"   X "+amount);
        Menu.jListMenu.setModel(Menu.model);
        }
        else{
        //update menu in list
        DefaultListModel<String> newModel = new DefaultListModel<>();
        for (int i = 0; i <  Menu.model.getSize(); i++) {
            String Element = Menu.model.getElementAt(i);
            if(Element.split("X")[0].trim().equals(name)){
                newModel.addElement(name +"   X "+amount);
                continue;
            }
            newModel.addElement(Element);
        }
        
        Menu.jListMenu.setModel(newModel);
        }

        Menu.menuNow.put(name,amount);
        Menu.setTotalPrice();
        Index.jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
    jTabbedPane1.setSelectedIndex(0);        
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        jFormattedAmount.setText("");
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jFormattedAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedAmountKeyTyped
         char input = evt.getKeyChar();
        if(!(Character.isDigit(input))){
            evt.consume();//stop input
            return;
        }
        int len =  jFormattedAmount.getText().length();
        if(len >=4 ){
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedAmountKeyTyped

    private void jFormattedAmountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedAmountMouseClicked
        jFormattedAmount.setText("");
    }//GEN-LAST:event_jFormattedAmountMouseClicked

    private void jFormattedAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedAmountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBack;
    public static javax.swing.JFormattedTextField jFormattedAmount;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    public static javax.swing.JLabel jLabelName;
    public static javax.swing.JLabel jLabelPrice;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
