/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import main.Index;
import main.Menu;

/**
 *
 * @author DELL
 */
public class BillQrCode extends javax.swing.JPanel {

    /**
     * Creates new form BillQrCode
     */
    public BillQrCode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelQrCode = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonNext = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelQrCode1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(235, 235, 235));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Scan to pay with QR Prompt Pay");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 650, 400, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Name : Phiraphat Oonkhong");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 690, 400, -1));

        jLabelQrCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQrCode.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelQrCode.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(jLabelQrCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 470, 460));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNext.setBackground(new java.awt.Color(244, 103, 0));
        jButtonNext.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jButtonNext.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNext.setText("Succeed");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, 190, 70));

        jButtonBack.setBackground(new java.awt.Color(244, 103, 0));
        jButtonBack.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 190, 70));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 70, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon("DB\\Pic\\01.gif")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 560, 560));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 650, 730));

        jLabelQrCode1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQrCode1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelQrCode1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(jLabelQrCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 470, 460));

        jLabel2.setIcon(new javax.swing.ImageIcon("DB\\Pic\\11.png")); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        Menu.makeOrderTransition();
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        Index.jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButtonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabelQrCode;
    public static javax.swing.JLabel jLabelQrCode1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
