/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import javax.swing.JOptionPane;
import main.Index;
import main.Menu;

/**
 *
 * @author DELL
 */
public class BillCash extends javax.swing.JPanel {

    /**
     * Creates new form BillCash
     */
    public BillCash() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        LabelCashTotal = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabelChange = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldCash = new javax.swing.JTextField();
        jButtonNext = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButtonAffirm = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(235, 235, 235));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelCashTotal.setFont(new java.awt.Font("Comic Sans MS", 0, 22)); // NOI18N
        LabelCashTotal.setText("null");
        jPanel3.add(LabelCashTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 120, -1));

        jLabel32.setFont(new java.awt.Font("Comic Sans MS", 0, 22)); // NOI18N
        jLabel32.setText("Pay With Cash");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 160, -1));

        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel33.setText(" Cash");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabelChange.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabelChange.setText("0 bath");
        jLabelChange.setFocusable(false);
        jLabelChange.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabelChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, 40));

        jLabel35.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel35.setText("Change");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jLabel36.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel36.setText("Tip");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jTextFieldCash.setBackground(new java.awt.Color(244, 103, 0));
        jTextFieldCash.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jTextFieldCash.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCashActionPerformed(evt);
            }
        });
        jTextFieldCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCashKeyTyped(evt);
            }
        });
        jPanel3.add(jTextFieldCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 160, 40));

        jButtonNext.setBackground(new java.awt.Color(244, 103, 0));
        jButtonNext.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jButtonNext.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNext.setText("Succeed");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 210, 80));

        jButtonBack.setBackground(new java.awt.Color(244, 103, 0));
        jButtonBack.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 210, 80));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 22)); // NOI18N
        jLabel1.setText("Total : ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jTextField2.setBackground(new java.awt.Color(244, 103, 0));
        jTextField2.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setText("0.00");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 160, 40));

        jButtonAffirm.setBackground(new java.awt.Color(244, 103, 0));
        jButtonAffirm.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButtonAffirm.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAffirm.setText("affirm");
        jButtonAffirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAffirmActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAffirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 650, 490));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 730));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        Menu.makeOrderTransition();
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        Index.jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonAffirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAffirmActionPerformed
        int moneyGiven = Integer.parseInt(jTextFieldCash.getText());
        int price = Integer.parseInt(Menu.getTotalPrice());
        if (moneyGiven < price){
            JOptionPane.showMessageDialog(this,"you give less money than the purchase price ","",JOptionPane.ERROR_MESSAGE);
            return;
        }

        String Change = String.valueOf(moneyGiven - price);

        jLabelChange.setText( Change+" bath");
    }//GEN-LAST:event_jButtonAffirmActionPerformed

    private void jTextFieldCashKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCashKeyTyped
       if(!Character.isDigit(evt.getKeyChar())){
           evt.consume();
       }
    }//GEN-LAST:event_jTextFieldCashKeyTyped

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextFieldCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCashActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LabelCashTotal;
    private javax.swing.JButton jButtonAffirm;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    public static javax.swing.JLabel jLabelChange;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextFieldCash;
    // End of variables declaration//GEN-END:variables
}
