/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import main.Index;
import main.Menu;


/**
 *
 * @author DELL
 */
public class MenuGrid extends javax.swing.JPanel {

    /**
     * Creates new form MenuGrid
     */
    public int price;

    public MenuGrid() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImage = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(202, 210, 232));
        setMaximumSize(new java.awt.Dimension(300, 300));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(300, 300));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImage.setBackground(new java.awt.Color(51, 255, 0));
        jLabelImage.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 280, 230));

        jLabelName.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("Name Menu + Price");
        add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        String name = jLabelName.getText();
        AddMenu.jLabelName.setText(name);
        AddMenu.jLabelPrice.setText(String.valueOf(price));
        //set amount in jFormattedAmount ifไม่ได้อยู่ที่ orderไว  set 1 by default
        String  set = String.valueOf(Menu.menuNow.get(name));
        if(set.equals("null")){
            AddMenu.jFormattedAmount.setText("1");
        }
        else{
            AddMenu.jFormattedAmount.setText(set);
        }

        Index.jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabelImage;
    public javax.swing.JLabel jLabelName;
    // End of variables declaration//GEN-END:variables
}
